name: console
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  pub_api_client: ^3.1.1
  http: ^1.1.0
  yaml: ^3.1.2
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  path: ^1.9.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.12
